### ISSUE TITLE
Feature Request: Configuration option to destroy equipment being disenchanted

### ISSUE THREAD

**Issue by SodiumShine** [treekicker4/Enchantment-Transfer#2]
Like it says on the title, I think it would be a great idea if you could optionally require items be destroyed after having their enchantments transferred to a book. Right now, you can use gold equipment with its high enchantability as a kind of enchantment mule to limit the type of enchantments you get, with better odds than you'd get out of diamond or netherite. This itself is a good thing in my opinion, but after having done it a bunch I feel that having it come at the cost of the equipment would make the whole process feel better. In fact, it would even encourage this kind of behavior because you couldn't simply enchant and disenchant diamond/netherite gear without huge losses.

**Comment by treekicker4** [comment]
Hi SodiumShine, I forgot to close this but I did end up adding a config option "return item" that decides whether you get the item back or not. It's default is 1, so it returns the item, but you could set it to 0 so that the item is not returned!
