### ISSUE TITLE
Can't transfer echantment to book (possible modpack conflict)

### ISSUE THREAD

**Issue by WolWolffz** [treekicker4/Enchantment-Transfer#6]
Hello, sorry for bringing a modpack issue here, but i dont know where else to go.

The problem is: When i place, lets say, an enchanted chestplate in the anvil and then a book, the enchanted book appears at the exit slot for a split second but then turn to nothing with the red X.

My modpack mod list is [this one](https://pastebin.com/dZtEL6WZ), im using resource packs too. This list is all the mods from client and server side.

**Comment by WolWolffz** [comment]
welp my bad, the mod wasnt on the server side

**Comment by treekicker4** [comment]
Good to know there's nothing wrong with the mod, thank you so much for providing the reason so that others with similar behavior have a way of fixing it. Sorry I couldn't get around to this earlier, it's currently finals week! Thanks again for documenting.
